#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if and (eq .Values.global.userPlaneArchitecture "ulcl") $.Values.global.n9network.enabled }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.global.n9network.name }}-{{ include "free5gc-upf.fullname" $ }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": {{ .Values.global.n9network.type | quote }},
          "capabilities": { "ips": true },
          "master": {{ .Values.global.n9network.masterIf | quote }},
{{- if eq .Values.global.n9network.type "macvlan" }}
          "mode": "bridge",
{{- end }}
{{- if eq .Values.global.n9network.type "ipvlan" }}
          "mode": "l2",
{{- end }}
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "{{ .Values.global.n9network.gatewayIP }}"
              }
            ]
          }
        }
{{- if eq .Values.global.n9network.type "macvlan" -}}
        , {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
{{- end }}
      ]
    }'
{{- end }}
